# Generated by Django 4.2.5 on 2023-11-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='微信账号的openid'),
        ),
    ]
