# Generated by Django 4.2.5 on 2023-12-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_user_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechatAvatarUrl',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信头像url'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechatName',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信昵称'),
        ),
    ]
