# Generated by Django 4.2.5 on 2023-12-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_user_wechatavatarurl_user_wechatname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wechatAvatarUrl',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='微信头像url'),
        ),
    ]
